FROM debian:stable-slim
RUN apt-get update
RUN apt-get upgrade -y

RUN apt install -y build-essential zlib1g-dev libncurses5-dev libgdbm-dev libnss3-dev libssl-dev libreadline-dev libffi-dev libsqlite3-dev wget libbz2-dev python3-pip
RUN apt-get update && apt-get install -y \
    python3-dev \
    libsdl2-dev \
    libsdl2-image-dev \
    libsdl2-mixer-dev \
    libsdl2-ttf-dev \
    libfreetype6-dev \
    libportmidi-dev \
    && rm -rf /var/lib/apt/lists/*

# Download Python interpreter code and unpack it
RUN wget https://www.python.org/ftp/python/3.10.8/Python-3.10.8.tgz
RUN tar -xf Python-3.10.*.tgz

# Build the Python interpreter
RUN cd Python-3.10.8 && ./configure --enable-optimizations && make && make altinstall

# Build the Python interpreter
COPY requirements.txt ./
RUN python3.10 -m pip install -r requirements.txt
# Copy our code into the image
COPY main.py main.py

# Copy our data dependencies
COPY images/ images/
COPY audio/ audio/

# Run our Python script
CMD ["python3.10", "main.py"]
